version: '3'

services:
  web:
    build: ./apps
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=babtis_user
      - POSTGRES_PASSWORD=babtis_password
      - POSTGRES_DB=babtis_db_dev

volumes:
  postgres_data: